"""CI drift ratchet for ``docs/api/facade-actions.md`` (#519).

``docs/api/facade-actions.md`` is AUTO-GENERATED by
``scripts/generate_facade_actions_doc.py`` from the live facade registry
(action maps + inner tool schemas + CLI parity crosswalk). This test
regenerates the document in-memory and compares it byte-for-byte to the
committed artifact — same ratchet philosophy as #496: the doc can never
silently lag the schema surface.

On mismatch the fix is mechanical::

    uv run python scripts/generate_facade_actions_doc.py

and commit the regenerated file.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[3]
SCRIPT_PATH = PROJECT_ROOT / "scripts" / "generate_facade_actions_doc.py"
DOC_PATH = PROJECT_ROOT / "docs" / "api" / "facade-actions.md"
REGEN_COMMAND = "uv run python scripts/generate_facade_actions_doc.py"


def _load_generator():
    """Load the generator script as a module (scripts/ is not a package)."""
    assert SCRIPT_PATH.is_file(), f"generator script missing: {SCRIPT_PATH}"
    spec = importlib.util.spec_from_file_location(
        "generate_facade_actions_doc", SCRIPT_PATH
    )
    assert spec is not None and spec.loader is not None, f"cannot load {SCRIPT_PATH}"
    module = importlib.util.module_from_spec(spec)
    # Register before exec: the script defines a dataclass under
    # ``from __future__ import annotations``, and dataclass processing looks
    # the module up in ``sys.modules`` to resolve the string annotations.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_facade_actions_doc_exists() -> None:
    """The generated artifact must be committed alongside the generator."""
    assert DOC_PATH.is_file(), (
        f"{DOC_PATH} is missing — generate and commit it: {REGEN_COMMAND}"
    )


@pytest.mark.slow_ok  # Loads the full facade registry + inner schemas; loaded CI runners can exceed 5s.
def test_facade_actions_doc_matches_generator() -> None:
    """Committed doc == in-memory regeneration (byte-for-byte)."""
    module = _load_generator()
    expected = module.generate_markdown()
    committed = DOC_PATH.read_text(encoding="utf-8")
    assert committed == expected, (
        "docs/api/facade-actions.md has drifted from the facade registry / "
        f"inner tool schemas. Regenerate it and commit: {REGEN_COMMAND}"
    )


@pytest.mark.slow_ok  # Loads the full facade registry + inner schemas; loaded CI runners can exceed 5s.
def test_facade_actions_surface_pins() -> None:
    """Exact pins on the documented surface (conscious re-pin on change).

    * 8 facades, 71 routable actions total (measured 2026-06-13).
    * Exactly 4 actions have no authoritative CLI twin — they are new-only
      MCP capabilities with no entry in ``facade_map.NEW_ACTION_PARITY`` nor
      a legacy name in the agent-contracts ``tool_to_cli`` parity table. A
      new action landing without CLI parity must either add a parity entry
      or consciously extend this pin.
    """
    module = _load_generator()
    rows_by_facade = module.collect_rows()

    assert sorted(rows_by_facade) == [
        "edit",
        "health",
        "index",
        "nav",
        "project",
        "search",
        "structure",
        "viz",
    ]
    total_actions = sum(len(rows) for rows in rows_by_facade.values())
    assert total_actions == 71

    gaps = sorted(
        (facade, row.action)
        for facade, rows in rows_by_facade.items()
        for row in rows
        if row.cli_twin == module.NO_CLI_TWIN
    )
    assert gaps == [
        ("search", "select"),
        ("search", "subscribe"),
        ("search", "unsubscribe"),
        ("structure", "signatures"),
    ]
