# Comprehensive Analyzer Setup Action
#
# Centralizes Python, uv, caching, and system dependency setup.

name: 'Setup Analyzer Environment'
description: 'Sets up Python, uv with caching, and system dependencies like fd/ripgrep'

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.11'
  os:
    description: 'Operating system (ubuntu-latest, windows-latest, macos-latest)'
    required: true
  install-sys-deps:
    description: 'Whether to install system dependencies (fd, ripgrep)'
    required: false
    default: 'true'
  uv-sync:
    description: 'Whether to run uv sync'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install uv and Python
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        python-version: ${{ inputs.python-version }}

    - name: Setup System Dependencies
      if: inputs.install-sys-deps == 'true'
      uses: ./.github/actions/setup-system
      with:
        os: ${{ inputs.os }}

    - name: Run uv sync
      if: inputs.uv-sync == 'true'
      run: uv sync --all-extras
      shell: bash

    - name: Set Environment Variables
      run: |
        echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV
        echo "PYTHONUTF8=1" >> $GITHUB_ENV
      shell: bash
