"""
Pytest test renderer for test generation.

Renders TestCase objects into pytest-compatible Python code.
"""

from __future__ import annotations

from pathlib import Path

from tree_sitter_analyzer.test_gen.generator import FuncInfo, TestCase


class PytestRenderer:
    """
    Renders test cases as pytest-compatible Python code.

    Features:
    - Generates import statements
    - Handles edge cases (None, empty strings, boundaries)
    - Includes decorators with warnings for non-testable functions
    - Produces syntactically valid pytest code
    """

    def __init__(self, module_path: str) -> None:
        """
        Initialize the pytest renderer.

        Args:
            module_path: Module path for import generation (e.g., "src.auth.auth")
        """
        self.module_path = module_path

    def render_test_file(self, func_infos: list[FuncInfo], test_cases: dict[str, list[TestCase]]) -> str:
        """
        Render a complete test file.

        Args:
            func_infos: List of function information
            test_cases: Dictionary mapping function names to test cases

        Returns:
            Complete pytest test file content
        """
        lines: list[str] = []

        # File header
        lines.append('"""')
        lines.append(f"Auto-generated tests for {self.module_path}")
        lines.append("")
        lines.append("Generated by tree-sitter-analyzer test generation engine")
        lines.append('"""')
        lines.append("")

        # Imports
        lines.extend(self._generate_imports(func_infos))
        lines.append("")

        # Test class (optional, for organization)
        if len(func_infos) > 1:
            lines.append(f'class Test{self._module_path_to_class_name()}:')
            lines.append('    """')
            lines.append(f"    Tests for {self.module_path}")
            lines.append('    """')
            lines.append("")
            indent = "    "
        else:
            indent = ""

        # Generate test cases for each function
        for func_info in func_infos:
            func_test_cases = test_cases.get(func_info.name, [])
            lines.extend(self._render_function_tests(func_info, func_test_cases, indent))
            lines.append("")

        return "\n".join(lines)

    def _generate_imports(self, func_infos: list[FuncInfo]) -> list[str]:
        """Generate import statements for the test file."""
        lines: list[str] = []

        # pytest import
        lines.append("import pytest")
        lines.append("")

        # Import the functions under test
        if self.module_path:
            lines.append(f"from {self.module_path} import (")
            for func_info in func_infos:
                lines.append(f"    {func_info.name},")
            lines.append(")")
        else:
            # Fallback: import all
            lines.append("# TODO: Add imports for functions under test")

        return lines

    def _get_module_name(self) -> str:
        """Get the module name from the module path."""
        # Extract the last component (e.g., "src.auth.auth" -> "auth")
        parts = self.module_path.split(".")
        return parts[-1] if parts else self.module_path

    def _module_path_to_class_name(self) -> str:
        """Convert module path to class name (e.g., "src.auth.auth" -> "SrcAuthAuth")."""
        parts = self.module_path.split(".")
        return "".join(p.title() for p in parts) if parts else "TestModule"

    def _render_function_tests(self, func_info: FuncInfo, test_cases: list[TestCase], indent: str) -> list[str]:
        """Render test cases for a single function."""
        lines: list[str] = []

        # Decorator warning if function has non-testable decorators
        if func_info.decorators:
            non_testable = [d for d in func_info.decorators if d in ("staticmethod", "classmethod", "property")]
            if non_testable:
                lines.append(f"{indent}# WARNING: Function has {', '.join(non_testable)} decorator(s)")
                lines.append(f"{indent}# Tests may need to be adjusted for instance/class methods")
                lines.append(f"{indent}#")

        for test_case in test_cases:
            lines.extend(self._render_test_case(test_case, func_info, indent))
            lines.append("")

        return lines

    def _render_test_case(self, test_case: TestCase, func_info: FuncInfo, indent: str) -> list[str]:
        """Render a single test case."""
        lines: list[str] = []

        # Test function signature
        lines.append(f"{indent}def {test_case.test_name}(self) -> None:")
        lines.append(f'{indent}    """')
        lines.append(f'{indent}    {test_case.comment}')
        lines.append(f'{indent}    """')

        # Test setup (if any)
        if test_case.setup:
            for setup_line in test_case.setup.split("\n"):
                lines.append(f"{indent}    {setup_line}")

        # Function call
        for call_line in test_case.call.split("\n"):
            lines.append(f"{indent}    {call_line}")

        # Assertions
        for assertion in test_case.assertions:
            lines.append(f"{indent}    {assertion}")

        return lines

    def render_test_case(self, test_case: TestCase, func_info: FuncInfo) -> str:
        """
        Render a single test case as a string.

        Args:
            test_case: Test case to render
            func_info: Function information for context

        Returns:
            Rendered test case code
        """
        lines = self._render_test_case(test_case, func_info, "")
        return "\n".join(lines)

    def validate_syntax(self, code: str) -> tuple[bool, str | None]:
        """
        Validate that the generated code is syntactically valid Python.

        Args:
            code: Generated test code

        Returns:
            Tuple of (is_valid, error_message)
        """
        try:
            compile(code, "<string>", "exec")
            return True, None
        except SyntaxError as e:
            return False, f"Line {e.lineno}: {e.msg}"
        except Exception as e:
            return False, str(e)


def render_test_file_to_path(
    func_infos: list[FuncInfo],
    test_cases: dict[str, list[TestCase]],
    module_path: str,
    output_path: str | Path,
) -> None:
    """
    Render a test file and write it to disk.

    Args:
        func_infos: List of function information
        test_cases: Dictionary mapping function names to test cases
        module_path: Module path for import generation
        output_path: Path to write the test file
    """
    renderer = PytestRenderer(module_path)
    content = renderer.render_test_file(func_infos, test_cases)

    # Validate syntax before writing
    is_valid, error = renderer.validate_syntax(content)
    if not is_valid:
        raise ValueError(f"Generated code has syntax error: {error}")

    output_path_obj = Path(output_path)
    output_path_obj.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path_obj, "w") as f:
        f.write(content)
