"""Bounded subprocess and JUnit adapters for the dogfood sprint."""

from __future__ import annotations

import json
import subprocess
from collections.abc import Callable
from pathlib import Path
from typing import Any
from xml.etree import ElementTree as ET  # nosec B405 - local pytest report only

ProcessRunner = Callable[..., Any]
Clock = Callable[[], float]
ClaimResult = dict[str, Any]
_MAX_CLAIM_REPORT_BYTES = 8 * 1024 * 1024


def run_tsa(
    args: list[str],
    *,
    root: Path,
    tool_bin: list[str],
    timeout: int,
    process_runner: ProcessRunner,
    clock: Clock,
) -> dict[str, Any]:
    """Run one TSA JSON command and normalize process failures."""
    command = [*tool_bin, *args, "--output-format", "json"]
    started_at = clock()
    try:
        process = process_runner(
            command,
            cwd=str(root),
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return _process_error(timeout, f"timeout after {timeout}s")
    except Exception as exc:
        return _process_error(0, str(exc))

    elapsed = round(clock() - started_at, 2)
    data = _process_data(process.stdout, process.stderr)
    return {
        "status": "ok" if process.returncode == 0 else "error",
        "elapsed_s": elapsed,
        "data": data,
    }


def _process_error(elapsed_s: int, message: str) -> dict[str, Any]:
    return {
        "status": "error",
        "elapsed_s": elapsed_s,
        "data": {"error": message},
    }


def _process_data(stdout: str, stderr: str) -> dict[str, Any]:
    if not stdout.strip():
        return {"stderr": stderr[:1000]} if stderr else {}
    try:
        value = json.loads(stdout)
    except json.JSONDecodeError:
        return {"raw": stdout[:2000]}
    return value if isinstance(value, dict) else {"result": value}


def run_claim_tests(
    *,
    root: Path,
    pytest_bin: list[str],
    process_runner: ProcessRunner,
    report_parser: Callable[[Path], list[ClaimResult]],
) -> list[ClaimResult]:
    """Run the claim benchmark suite and parse its bounded result report."""
    report_path = root / "dogfood-claims-report.xml"
    if report_path.exists():
        report_path.unlink()
    command = [
        *pytest_bin,
        "tests/benchmarks/claims/",
        "-v",
        "--tb=line",
        "--no-header",
        "-q",
        "--override-ini=addopts=--strict-markers --timeout=60",
        "--junit-xml=dogfood-claims-report.xml",
    ]
    try:
        process = process_runner(
            command,
            cwd=str(root),
            capture_output=True,
            text=True,
            timeout=120,
            check=False,
        )
    except Exception as exc:
        return [_claim_suite_error(str(exc))]

    if report_path.exists():
        try:
            return report_parser(report_path)
        except ET.ParseError as exc:
            return [_claim_suite_error(f"invalid junit xml: {exc}")]
    fallback = _parse_claim_stdout(process.stdout)
    if fallback:
        return fallback
    status = "error" if process.returncode != 0 else "unknown"
    message = (process.stderr or process.stdout or "")[:500]
    return [{"test": "claims_suite", "status": status, "message": message}]


def _claim_suite_error(message: str) -> ClaimResult:
    return {"test": "claims_suite", "status": "error", "message": message}


def _parse_claim_stdout(stdout: str) -> list[ClaimResult]:
    results: list[ClaimResult] = []
    for line in stdout.splitlines():
        status = _status_from_pytest_line(line)
        if status is None:
            continue
        parts = line.strip().split()
        results.append(
            {
                "test": parts[0] if parts else "unknown",
                "status": status,
                "message": "",
            }
        )
    return results


def _status_from_pytest_line(line: str) -> str | None:
    for marker, status in (
        (" PASSED", "passed"),
        (" FAILED", "failed"),
        (" XFAIL", "xfail"),
        (" XPASS", "xpass"),
    ):
        if marker in line:
            return status
    return None


def parse_claim_junit_report(report_path: Path) -> list[ClaimResult]:
    """Parse pytest JUnit XML into the dogfood claim schema."""
    if report_path.stat().st_size > _MAX_CLAIM_REPORT_BYTES:
        raise ET.ParseError("claim report exceeds the 8 MiB safety bound")
    # The file is freshly generated by our fixed pytest command and size-bounded.
    root = ET.parse(report_path).getroot()  # nosec B314
    return [_parse_claim_case(case) for case in root.findall(".//testcase")]


def _parse_claim_case(case: ET.Element) -> ClaimResult:
    classname = case.get("classname", "")
    name = case.get("name", "unknown")
    test_id = f"{classname}::{name}" if classname else name
    failure = case.find("failure")
    if failure is not None:
        content = failure.get("message", "") + (failure.text or "")
        status = "xpass" if "xpass" in content.lower() else "failed"
        return _claim_result(test_id, status, failure)
    error = case.find("error")
    if error is not None:
        return _claim_result(test_id, "error", error)
    skipped = case.find("skipped")
    if skipped is not None:
        status = (
            "xfail"
            if (skipped.get("type") or "").lower() == "pytest.xfail"
            else "skipped"
        )
        return _claim_result(test_id, status, skipped)
    return {"test": test_id, "status": "passed", "message": ""}


def _claim_result(test_id: str, status: str, node: ET.Element) -> ClaimResult:
    message = (node.get("message") or node.text or "")[:500]
    return {"test": test_id, "status": status, "message": message}


def run_readme_counts(
    *,
    root: Path,
    pytest_bin: list[str],
    process_runner: ProcessRunner,
) -> dict[str, Any]:
    """Run the README-number verification step."""
    command = [
        *pytest_bin,
        "tests/",
        "-k",
        "readme_counts",
        "-v",
        "--no-header",
        "--override-ini=addopts=--strict-markers --timeout=30",
    ]
    try:
        process = process_runner(
            command,
            cwd=str(root),
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
        )
    except Exception as exc:
        return {
            "status": "error",
            "elapsed_s": 0,
            "data": {"error": str(exc)},
        }
    return {
        "status": "ok" if process.returncode == 0 else "error",
        "elapsed_s": 0,
        "data": {"output": process.stdout[-1000:]},
    }
