#!/usr/bin/env python3
"""RFC-0017 Phase 1 — per-module mutation baseline runner.

Usage:
    uv run python scripts/run_mutation_baseline.py [module_key]

module_key: one of ast_diff, semantic_change_classifier, facade_tool,
            query_symbol_search, toon_encoder  (default: ast_diff)

Runs mutmut on a single source file + its targeted tests, then prints
the surviving/killed/total count.  Results feed tests/effectiveness/BASELINE.md.

NOTE: mutmut uses os.fork — Linux only (ubuntu-latest in CI).
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

# Module -> (source file, targeted test paths)
MODULES: dict[str, tuple[str, list[str]]] = {
    "ast_diff": (
        "tree_sitter_analyzer/ast_diff.py",
        [
            "tests/unit/test_ast_diff.py",
            "tests/unit/test_ast_diff_tool.py",
        ],
    ),
    "semantic_change_classifier": (
        "tree_sitter_analyzer/semantic_change_classifier.py",
        [
            "tests/unit/test_semantic_change_classifier.py",
            "tests/unit/test_semantic_classify_tool.py",
        ],
    ),
    "facade_tool": (
        "tree_sitter_analyzer/mcp/tools/facade_tool.py",
        [
            "tests/unit/mcp/",
        ],
    ),
    "query_symbol_search": (
        "tree_sitter_analyzer/mcp/tools/query_symbol_search.py",
        [
            "tests/unit/mcp/",
        ],
    ),
    "toon_encoder": (
        "tree_sitter_analyzer/formatters/toon_encoder.py",
        [
            "tests/unit/mcp/test_output_cost_invariants.py",
        ],
    ),
}

PYPROJECT_TEMPLATE = """\
# Temporary pyproject.toml for per-module mutmut run (generated by scripts/run_mutation_baseline.py).
# Do not edit — regenerated on each run.
[tool.mutmut]
source_paths = ["{source_path}"]
pytest_add_cli_args_test_selection = {test_paths_toml}
pytest_add_cli_args = ["-n", "0", "-x", "--timeout=30", "-q"]
timeout_multiplier = 10.0
timeout_constant = 10.0
"""


def run_module(module_key: str, repo_root: Path) -> None:
    if module_key not in MODULES:
        print(f"Unknown module: {module_key}. Choose from: {list(MODULES)}")
        sys.exit(1)

    source_path, test_paths = MODULES[module_key]
    test_paths_toml = "[" + ", ".join(f'"{p}"' for p in test_paths) + "]"

    # Write a temporary pyproject.toml stub in a temp directory, then run
    # mutmut from there with the real source accessible via the PYTHONPATH.
    # Simpler: mutmut reads pyproject.toml from CWD. We swap it temporarily.
    real_pyproject = repo_root / "pyproject.toml"
    backup = repo_root / "pyproject.toml.mutation-bak"

    content = PYPROJECT_TEMPLATE.format(
        source_path=source_path,
        test_paths_toml=test_paths_toml,
    )

    # Create a minimal pyproject.toml that only has [tool.mutmut] — mutmut
    # only reads that section, so it doesn't need the full build config.
    minimal_pyproject = repo_root / "pyproject_mutmut_tmp.toml"
    minimal_pyproject.write_text(content, encoding="utf-8")

    # Back up real pyproject.toml, swap in minimal, run, restore.
    shutil.copy2(real_pyproject, backup)
    try:
        shutil.copy2(minimal_pyproject, real_pyproject)
        print(f"\n=== Running mutmut on {source_path} ===")
        print(f"    Tests: {test_paths}")
        result = subprocess.run(
            ["uv", "run", "mutmut", "run"],
            cwd=repo_root,
            capture_output=False,
        )
        print(f"\n=== mutmut run exit code: {result.returncode} ===")

        # Collect results
        print(f"\n=== Results for {module_key} ===")
        subprocess.run(
            ["uv", "run", "mutmut", "results"],
            cwd=repo_root,
        )
    finally:
        shutil.copy2(backup, real_pyproject)
        backup.unlink(missing_ok=True)
        minimal_pyproject.unlink(missing_ok=True)


def main() -> None:
    module_key = sys.argv[1] if len(sys.argv) > 1 else "ast_diff"
    repo_root = Path(__file__).parent.parent.resolve()
    run_module(module_key, repo_root)


if __name__ == "__main__":
    main()
